
/*
 * ComponentMain.cpp
 *
 *  Created on: Thursday, 30. January 2014 04:16PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleTrottleEffort(const config::LLI::sub::TrottleEffort& msg)
{
	std::cout<< "LLI say:" << msg.data << std::endl;
}
	

void ComponentMain::handleSteeringEffort(const config::LLI::sub::SteeringEffort& msg)
{
	std::cout<< "LLI say:" << msg.data << std::endl;
}
	

void ComponentMain::handleJointsEffort(const config::LLI::sub::JointsEffort& msg)
{
	std::cout<< "LLI say:" << msg.data << std::endl;
}
	

void ComponentMain::handleTeleoperation(const config::LLI::sub::Teleoperation& msg)
{
	std::cout<< "LLI say:" << msg.data << std::endl;
}
	

void ComponentMain::publishTeleoperation(config::LLI::pub::Teleoperation& msg)
{
	_roscomm->publishTeleoperation(msg);
}
	

void ComponentMain::publishTrottleEffort(config::LLI::pub::TrottleEffort& msg)
{
	_roscomm->publishTrottleEffort(msg);
}
	

void ComponentMain::publishSteeringEffort(config::LLI::pub::SteeringEffort& msg)
{
	_roscomm->publishSteeringEffort(msg);
}
	

void ComponentMain::publishJointsEffort(config::LLI::pub::JointsEffort& msg)
{
	_roscomm->publishJointsEffort(msg);
}
	
