
/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 30. January 2014 03:54PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();

	void publishSensor_SICK(config::SENSORS::pub::Sensor_SICK& msg);
	void publishSensor_IBEO(config::SENSORS::pub::Sensor_IBEO& msg);
	void publishSensor_CAM_R(config::SENSORS::pub::Sensor_CAM_R& msg);
	void publishSensor_CAM_L(config::SENSORS::pub::Sensor_CAM_L& msg);
	void publishSensor_WIRE(config::SENSORS::pub::Sensor_WIRE& msg);
	void publishSensor_INSGPS(config::SENSORS::pub::Sensor_INSGPS& msg);
};
#endif /* COMPONENTMAIN_H_ */
