
/*
 * ComponentMain.cpp
 *
 *  Created on: Thursday, 06. February 2014 04:09PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}


void ComponentMain::publishSensor_SICK_1(config::SENSORS::pub::Sensor_SICK_1& msg)
{
	_roscomm->publishSensor_SICK_1(msg);
}
	

void ComponentMain::publishSensor_SICK_2(config::SENSORS::pub::Sensor_SICK_2& msg)
{
	_roscomm->publishSensor_SICK_2(msg);
}
	

void ComponentMain::publishSensor_IBEO_1(config::SENSORS::pub::Sensor_IBEO_1& msg)
{
	_roscomm->publishSensor_IBEO_1(msg);
}
	

void ComponentMain::publishSensor_IBEO_2(config::SENSORS::pub::Sensor_IBEO_2& msg)
{
	_roscomm->publishSensor_IBEO_2(msg);
}
	

void ComponentMain::publishSensor_IBEO_3(config::SENSORS::pub::Sensor_IBEO_3& msg)
{
	_roscomm->publishSensor_IBEO_3(msg);
}
	

void ComponentMain::publishSensor_IBEO_4(config::SENSORS::pub::Sensor_IBEO_4& msg)
{
	_roscomm->publishSensor_IBEO_4(msg);
}
	

void ComponentMain::publishSensor_CAM_R(config::SENSORS::pub::Sensor_CAM_R& msg)
{
	_roscomm->publishSensor_CAM_R(msg);
}
	

void ComponentMain::publishSensor_CAM_L(config::SENSORS::pub::Sensor_CAM_L& msg)
{
	_roscomm->publishSensor_CAM_L(msg);
}
	

void ComponentMain::publishSensor_WIRE(config::SENSORS::pub::Sensor_WIRE& msg)
{
	_roscomm->publishSensor_WIRE(msg);
}
	

void ComponentMain::publishSensor_GPS(config::SENSORS::pub::Sensor_GPS& msg)
{
	_roscomm->publishSensor_GPS(msg);
}
	

void ComponentMain::publishSensor_INS(config::SENSORS::pub::Sensor_INS& msg)
{
	_roscomm->publishSensor_INS(msg);
}
	
void ComponentMain::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	_roscomm->publishTransform(_tf, srcFrame, distFrame);
}
tf::StampedTransform ComponentMain::getLastTrasform(std::string srcFrame, std::string distFrame){
	return _roscomm->getLastTrasform(srcFrame, distFrame);;
}
