
/*
 * RosComm.h
 *
 *  Created on: Thursday, 30. January 2014 06:41PM
 *      Author: autogenerated
 */
#ifndef ROSCOMM_H_
#define ROSCOMM_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
class ComponentMain;
class RosComm {
  ComponentMain   * _comp;
  ros::NodeHandle _nh;
	ros::Subscriber _sub_ExecuteWorkSequenceCommand;
	ros::Subscriber _sub_PosAttVel;
	ros::Subscriber _sub_WiresLengths;
	ros::Publisher  _pub_BladePosition;
	ros::Publisher  _pub_TrottleEffort;
	ros::Publisher  _pub_SteeringEffort;
	ros::Publisher  _pub_JointsEffort;

public:
	RosComm(ComponentMain* comp,int argc,char** argv);
	virtual ~RosComm();
	void ExecuteWorkSequenceCommandCallback(const config::WSM::sub::ExecuteWorkSequenceCommand::ConstPtr &msg);
	void PosAttVelCallback(const config::WSM::sub::PosAttVel::ConstPtr &msg);
	void WiresLengthsCallback(const config::WSM::sub::WiresLengths::ConstPtr &msg);
	void publishBladePosition( config::WSM::pub::BladePosition &msg);
	void publishTrottleEffort( config::WSM::pub::TrottleEffort &msg);
	void publishSteeringEffort( config::WSM::pub::SteeringEffort &msg);
	void publishJointsEffort( config::WSM::pub::JointsEffort &msg);

};
#endif /* ROSCOMM_H_ */
