
/*
 * RosComm.cpp
 *
 *  Created on: Thursday, 30. January 2014 03:54PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
{
  ros::init(argc,argv,"PP_node");
  _comp=comp;
	_sub_Map=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"WSM","ExecuteWorkSequenceCommand","sub"), 10, &RosComm::ExecuteWorkSequenceCommandCallback,this));
	_sub_Map=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"WSM","PosAttVel","sub"), 10, &RosComm::PosAttVelCallback,this));
	_sub_Map=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"WSM","WiresLengths","sub"), 10, &RosComm::WiresLengthsCallback,this));
	_pub_BladePosition=ros::Publisher(_nh.advertise<config::WSM::pub::BladePosition>(fetchParam(&_nh,"WSM","BladePosition","pub"),10));
	_pub_TrottleEffort=ros::Publisher(_nh.advertise<config::WSM::pub::TrottleEffort>(fetchParam(&_nh,"WSM","TrottleEffort","pub"),10));
	_pub_SteeringEffort=ros::Publisher(_nh.advertise<config::WSM::pub::SteeringEffort>(fetchParam(&_nh,"WSM","SteeringEffort","pub"),10));
	_pub_JointsEffort=ros::Publisher(_nh.advertise<config::WSM::pub::JointsEffort>(fetchParam(&_nh,"WSM","JointsEffort","pub"),10));
}
RosComm::~RosComm()
{
}

void RosComm::ExecuteWorkSequenceCommandCallback(const config::WSM::sub::ExecuteWorkSequenceCommand::ConstPtr &msg)
{
	_comp->handleExecuteWorkSequenceCommand(*msg);
}
	

void RosComm::PosAttVelCallback(const config::WSM::sub::PosAttVel::ConstPtr &msg)
{
	_comp->handlePosAttVel(*msg);
}
	

void RosComm::WiresLengthsCallback(const config::WSM::sub::WiresLengths::ConstPtr &msg)
{
	_comp->handleWiresLengths(*msg);
}
	

void RosComm::publishBladePosition( config::WSM::pub::BladePosition &msg)
{
	_pub_BladePosition.publish(msg);
}
	

void RosComm::publishTrottleEffort( config::WSM::pub::TrottleEffort &msg)
{
	_pub_TrottleEffort.publish(msg);
}
	

void RosComm::publishSteeringEffort( config::WSM::pub::SteeringEffort &msg)
{
	_pub_SteeringEffort.publish(msg);
}
	

void RosComm::publishJointsEffort( config::WSM::pub::JointsEffort &msg)
{
	_pub_JointsEffort.publish(msg);
}
	
