
/*
 * RosComm.cpp
 *
 *  Created on: Wednesday, 19. February 2014 02:59PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
#include <tf/transform_broadcaster.h>
#include <tf/transform_listener.h>
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
	: _inited(init(argc, argv)), _comp(comp)
{
	_sub_IEDLocation=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"OCU","IEDLocation","sub"), 10, &RosComm::IEDLocationCallback,this));
	_sub_MissionAcceptance=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"OCU","MissionAcceptance","sub"), 10, &RosComm::MissionAcceptanceCallback,this));
	_sub_LocalPath=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"OCU","LocalPath","sub"), 10, &RosComm::LocalPathCallback,this));
	_sub_BladePosition=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"OCU","BladePosition","sub"), 10, &RosComm::BladePositionCallback,this));
	_sub_Map=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"OCU","Map","sub"), 10, &RosComm::MapCallback,this));
	_sub_PerVelocity=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"OCU","PerVelocity","sub"), 10, &RosComm::PerVelocityCallback,this));
	_sub_Location=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"OCU","Location","sub"), 10, &RosComm::LocationCallback,this));
	_pub_CustomIED=ros::Publisher(_nh.advertise<config::OCU::pub::CustomIED>(fetchParam(&_nh,"OCU","CustomIED","pub"),10));
	_pub_PositionUpdate=ros::Publisher(_nh.advertise<config::OCU::pub::PositionUpdate>(fetchParam(&_nh,"OCU","PositionUpdate","pub"),10));
	_pub_AssignNavTask=ros::Publisher(_nh.advertise<config::OCU::pub::AssignNavTask>(fetchParam(&_nh,"OCU","AssignNavTask","pub"),10));
	_pub_AssignManTask=ros::Publisher(_nh.advertise<config::OCU::pub::AssignManTask>(fetchParam(&_nh,"OCU","AssignManTask","pub"),10));
	_pub_AssignMission=ros::Publisher(_nh.advertise<config::OCU::pub::AssignMission>(fetchParam(&_nh,"OCU","AssignMission","pub"),10));
	_pub_diagnostic=ros::Publisher(_nh.advertise<diagnostic_msgs::DiagnosticArray>("/diagnostic",100));
	_maintains.add_thread(new boost::thread(boost::bind(&RosComm::heartbeat,this)));
}
RosComm::~RosComm()
{
}
bool RosComm::init(int argc,char** argv){
	ros::init(argc,argv,"OCU_node");
	return true;
}


void RosComm::IEDLocationCallback(const config::OCU::sub::IEDLocation::ConstPtr &msg)
{
	_comp->handleIEDLocation(*msg);
}
	

void RosComm::MissionAcceptanceCallback(const config::OCU::sub::MissionAcceptance::ConstPtr &msg)
{
	_comp->handleMissionAcceptance(*msg);
}
	

void RosComm::LocalPathCallback(const config::OCU::sub::LocalPath::ConstPtr &msg)
{
	_comp->handleLocalPath(*msg);
}
	

void RosComm::BladePositionCallback(const config::OCU::sub::BladePosition::ConstPtr &msg)
{
	_comp->handleBladePosition(*msg);
}
	

void RosComm::MapCallback(const config::OCU::sub::Map::ConstPtr &msg)
{
	_comp->handleMap(*msg);
}
	

void RosComm::PerVelocityCallback(const config::OCU::sub::PerVelocity::ConstPtr &msg)
{
	_comp->handlePerVelocity(*msg);
}
	

void RosComm::LocationCallback(const config::OCU::sub::Location::ConstPtr &msg)
{
	_comp->handleLocation(*msg);
}
	

void RosComm::publishCustomIED( config::OCU::pub::CustomIED &msg)
{
	_pub_CustomIED.publish(msg);
}
	

void RosComm::publishPositionUpdate( config::OCU::pub::PositionUpdate &msg)
{
	_pub_PositionUpdate.publish(msg);
}
	

void RosComm::publishAssignNavTask( config::OCU::pub::AssignNavTask &msg)
{
	_pub_AssignNavTask.publish(msg);
}
	

void RosComm::publishAssignManTask( config::OCU::pub::AssignManTask &msg)
{
	_pub_AssignManTask.publish(msg);
}
	

void RosComm::publishAssignMission( config::OCU::pub::AssignMission &msg)
{
	_pub_AssignMission.publish(msg);
}
	
void RosComm::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	static tf::TransformBroadcaster br;
	br.sendTransform(tf::StampedTransform(_tf, ros::Time::now(), srcFrame, distFrame));
}
tf::StampedTransform RosComm::getLastTrasform(std::string srcFrame, std::string distFrame){
	tf::StampedTransform _tf;
	static tf::TransformListener listener;
	try {
	    listener.waitForTransform(distFrame, srcFrame, ros::Time(0), ros::Duration(10.0) );
	    listener.lookupTransform(distFrame, srcFrame, ros::Time(0), _tf);
	} catch (tf::TransformException& ex) {
	    ROS_ERROR("%s",ex.what());
	}
	return _tf;
}
void RosComm::publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report){
	diagnostic_msgs::DiagnosticArray msg;
	msg.status.push_back(_report);
	_pub_diagnostic.publish(msg);
}
void RosComm::publishDiagnostic(const std_msgs::Header& header, const diagnostic_msgs::DiagnosticStatus& _report){
	diagnostic_msgs::DiagnosticArray msg;
	msg.header = header;
	msg.status.push_back(_report);
	_pub_diagnostic.publish(msg);
}
void RosComm::heartbeat(){
	using namespace boost::posix_time;
	ros::Publisher _pub = _nh.advertise<std_msgs::String>("/heartbeat", 10);
	double hz = HEARTBEAT_FREQUANCY;
	while(ros::ok()){
		boost::system_time stop_time = boost::get_system_time() + milliseconds((1/hz)*1000);
		std_msgs::String msg;
		msg.data = "OCU";
		_pub.publish(msg);
	    boost::this_thread::sleep(stop_time);
	}
}
