
/*
 * ComponentMain.h
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
#include <tf/tf.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleIEDDetectionEvent(const config::IEDSIM::sub::IEDDetectionEvent& msg);
	void handleIEDLocation(const config::IEDSIM::sub::IEDLocation& msg);
	void publishIEDDetectionEvent(config::IEDSIM::pub::IEDDetectionEvent& msg);
	void publishIEDLocation(config::IEDSIM::pub::IEDLocation& msg);
  void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
  tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
};
#endif /* COMPONENTMAIN_H_ */
