
/*
 * ComponentMain.cpp
 *
 *  Created on: Wednesday, 09. April 2014 08:18AM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
	_lg=new IEDSimLogic;
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleCustomIED(const config::IEDSIM::sub::CustomIED& msg)
{
	ROS_INFO("got location");
	_lg->setAtLocation(msg.location.x,msg.location.y,msg.location.z);
}
	

void ComponentMain::handleLocation(const config::IEDSIM::sub::Location& msg)
{
	if(_lg->isPoseWithinRadius(msg.pose.pose.position.x,msg.pose.pose.position.y,msg.pose.pose.position.z))
	{
		config::IEDSIM::pub::IEDLocation msg2;
		msg2.is_detected=1;
		msg2.location.x=_lg->m_x;
		msg2.location.y=_lg->m_y;
		msg2.location.z=_lg->m_z;
		publishIEDLocation(msg2);
	}
}
	

void ComponentMain::publishIEDLocation(config::IEDSIM::pub::IEDLocation& msg)
{
	_roscomm->publishIEDLocation(msg);
}
	
void ComponentMain::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	_roscomm->publishTransform(_tf, srcFrame, distFrame);
}
tf::StampedTransform ComponentMain::getLastTrasform(std::string srcFrame, std::string distFrame){
	return _roscomm->getLastTrasform(srcFrame, distFrame);
}
void ComponentMain::publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report){
	_roscomm->publishDiagnostic(_report);
}
void ComponentMain::publishDiagnostic(const std_msgs::Header& header, const diagnostic_msgs::DiagnosticStatus& _report){
	_roscomm->publishDiagnostic(header, _report);
}
