
/*
 * ComponentMain.h
 *
 *  Created on: Wednesday, 09. April 2014 08:18AM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
#include <tf/tf.h>
#include <boost/thread.hpp>
#include <std_msgs/String.h>
#include <ParameterTypes.h>
#include <tf/tf.h>
#include "IEDSimLogic.h"

class ComponentMain {
	bool _inited;

	  ros::NodeHandle _nh;
	  ros::Publisher _pub_diagnostic;
	  boost::thread_group _maintains;
		ros::Subscriber _sub_CustomIED;
		ros::Subscriber _sub_Location;
		ros::Publisher  _pub_IEDLocation;

	  bool init(int argc,char** argv);
	IEDSimLogic * _lg;

public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleCustomIED(const config::IEDSIM::sub::CustomIED& msg);
	void handleLocation(const config::IEDSIM::sub::Location& msg);
	void publishIEDLocation(config::IEDSIM::pub::IEDLocation& msg);
	void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
	tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
	void publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report);
	void publishDiagnostic(const std_msgs::Header& header, const diagnostic_msgs::DiagnosticStatus& _report);
	void heartbeat();
};
#endif /* COMPONENTMAIN_H_ */
