
/*
 * RosComm.cpp
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
#include <tf/transform_broadcaster.h>
#include <tf/transform_listener.h>
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
	: _inited(init(argc, argv)), _comp(comp)
{
	_sub_Camera=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"VO","Camera","sub"), 10, &RosComm::CameraCallback,this));
	_sub_INS=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"VO","INS","sub"), 10, &RosComm::INSCallback,this));
	_sub_TF=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"VO","TF","sub"), 10, &RosComm::TFCallback,this));
	_pub_PosAttVel=ros::Publisher(_nh.advertise<config::VO::pub::PosAttVel>(fetchParam(&_nh,"VO","PosAttVel","pub"),10));
}
RosComm::~RosComm()
{
}
bool RosComm::init(int argc,char** argv){
	ros::init(argc,argv,"VO_node");
	return true;
}


void RosComm::CameraCallback(const config::VO::sub::Camera::ConstPtr &msg)
{
	_comp->handleCamera(*msg);
}
	

void RosComm::INSCallback(const config::VO::sub::INS::ConstPtr &msg)
{
	_comp->handleINS(*msg);
}
	

void RosComm::TFCallback(const config::VO::sub::TF::ConstPtr &msg)
{
	_comp->handleTF(*msg);
}
	

void RosComm::publishPosAttVel( config::VO::pub::PosAttVel &msg)
{
	_pub_PosAttVel.publish(msg);
}
	
void RosComm::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	static tf::TransformBroadcaster br;
	br.sendTransform(tf::StampedTransform(_tf, ros::Time::now(), srcFrame, distFrame));
}
tf::StampedTransform RosComm::getLastTrasform(std::string srcFrame, std::string distFrame){
	tf::StampedTransform _tf;
	static tf::TransformListener listener;
	try {
	    listener.waitForTransform(distFrame, srcFrame, ros::Time(0), ros::Duration(10.0) );
	    listener.lookupTransform(distFrame, srcFrame, ros::Time(0), _tf);
	} catch (tf::TransformException& ex) {
	    ROS_ERROR("%s",ex.what());
	}
	return _tf;
}
