
/*
 * RosComm.h
 *
 *  Created on: Monday, 03. February 2014 03:30PM
 *      Author: autogenerated
 */
#ifndef ROSCOMM_H_
#define ROSCOMM_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
#include <tf/tf.h>
class ComponentMain;
class RosComm {
  bool _inited;
  ComponentMain   * _comp;
  ros::NodeHandle _nh;
	ros::Subscriber _sub_MiniMap;
	ros::Subscriber _sub_LocalPath;
	ros::Subscriber _sub_MaxSpeed;
	ros::Subscriber _sub_Odometry;
	ros::Subscriber _sub_WPDCommand;
	ros::Publisher  _pub_WPDSpeed;
	ros::Publisher  _pub_WPDDecisions;
	ros::Publisher  _pub_WPDState;
	ros::Publisher  _pub_WPDComponentState;

  bool init(int argc,char** argv);
public:
	RosComm(ComponentMain* comp,int argc,char** argv);
	virtual ~RosComm();
	void MiniMapCallback(const config::WPD::sub::MiniMap::ConstPtr &msg);
	void LocalPathCallback(const config::WPD::sub::LocalPath::ConstPtr &msg);
	void MaxSpeedCallback(const config::WPD::sub::MaxSpeed::ConstPtr &msg);
	void OdometryCallback(const config::WPD::sub::Odometry::ConstPtr &msg);
	void WPDCommandCallback(const config::WPD::sub::WPDCommand::ConstPtr &msg);
	void publishWPDSpeed( config::WPD::pub::WPDSpeed &msg);
	void publishWPDDecisions( config::WPD::pub::WPDDecisions &msg);
	void publishWPDState( config::WPD::pub::WPDState &msg);
	void publishWPDComponentState( config::WPD::pub::WPDComponentState &msg);

  void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
  tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
};
#endif /* ROSCOMM_H_ */
