
/*
 * RosComm.cpp
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
#include <tf/transform_broadcaster.h>
#include <tf/transform_listener.h>
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
	: _inited(init(argc, argv)), _comp(comp)
{
	_sub_MiniMap=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"WPD","MiniMap","sub"), 10, &RosComm::MiniMapCallback,this));
	_sub_LocalPathPlan=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"WPD","LocalPathPlan","sub"), 10, &RosComm::LocalPathPlanCallback,this));
	_sub_PosAttVel=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"WPD","PosAttVel","sub"), 10, &RosComm::PosAttVelCallback,this));
	_pub_Speed=ros::Publisher(_nh.advertise<config::WPD::pub::Speed>(fetchParam(&_nh,"WPD","Speed","pub"),10));
}
RosComm::~RosComm()
{
}
bool RosComm::init(int argc,char** argv){
	ros::init(argc,argv,"WPD_node");
	return true;
}


void RosComm::MiniMapCallback(const config::WPD::sub::MiniMap::ConstPtr &msg)
{
	_comp->handleMiniMap(*msg);
}
	

void RosComm::LocalPathPlanCallback(const config::WPD::sub::LocalPathPlan::ConstPtr &msg)
{
	_comp->handleLocalPathPlan(*msg);
}
	

void RosComm::PosAttVelCallback(const config::WPD::sub::PosAttVel::ConstPtr &msg)
{
	_comp->handlePosAttVel(*msg);
}
	

void RosComm::publishSpeed( config::WPD::pub::Speed &msg)
{
	_pub_Speed.publish(msg);
}
	
void RosComm::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	static tf::TransformBroadcaster br;
	br.sendTransform(tf::StampedTransform(_tf, ros::Time::now(), srcFrame, distFrame));
}
tf::StampedTransform RosComm::getLastTrasform(std::string srcFrame, std::string distFrame){
	tf::StampedTransform _tf;
	static tf::TransformListener listener;
	try {
	    listener.waitForTransform(distFrame, srcFrame, ros::Time(0), ros::Duration(10.0) );
	    listener.lookupTransform(distFrame, srcFrame, ros::Time(0), _tf);
	} catch (tf::TransformException& ex) {
	    ROS_ERROR("%s",ex.what());
	}
	return _tf;
}
