
/*
 * RosComm.h
 *
 *  Created on: Sunday, 02. February 2014 10:01AM
 *      Author: autogenerated
 */
#ifndef ROSCOMM_H_
#define ROSCOMM_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
class ComponentMain;
class RosComm {
  bool _inited;
  ComponentMain   * _comp;
  ros::NodeHandle _nh;
	ros::Subscriber _sub_MiniMap;
	ros::Subscriber _sub_LocalPathPlan;
	ros::Subscriber _sub_PosAttVel;
	ros::Publisher  _pub_Speed;

  bool init(int argc,char** argv);
public:
	RosComm(ComponentMain* comp,int argc,char** argv);
	virtual ~RosComm();
	void MiniMapCallback(const config::WPD::sub::MiniMap::ConstPtr &msg);
	void LocalPathPlanCallback(const config::WPD::sub::LocalPathPlan::ConstPtr &msg);
	void PosAttVelCallback(const config::WPD::sub::PosAttVel::ConstPtr &msg);
	void publishSpeed( config::WPD::pub::Speed &msg);

};
#endif /* ROSCOMM_H_ */
