
/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 30. January 2014 03:54PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleMissionStatus(const config::SSM::sub::MissionStatus& msg);
	void publishStatusData(config::SSM::pub::StatusData& msg);
};
#endif /* COMPONENTMAIN_H_ */
