
/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 27. February 2014 12:29PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
#include <tf/tf.h>
#include "../cognitao_v2/cognitao_v2.h"

class RosComm;
class ComponentMain {
	RosComm* _roscomm;
	cognitao::bus::RosEventQueue* _events;
	boost::mutex _mt;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleBladePosition(const config::SSM::sub::BladePosition& msg);
	void handleLocation(const config::SSM::sub::Location& msg);
	void handlePerVelocity(const config::SSM::sub::PerVelocity& msg);

	void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
	tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
	void publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report);
	void publishDiagnostic(const std_msgs::Header& header, const diagnostic_msgs::DiagnosticStatus& _report);

	void set_events(cognitao::bus::RosEventQueue* events);
	void rise_taskFinished();
	void rise_taskAborted();
	void rise_taskStarted();
	void rise_taskPaused();
	bool isClosed();
};
#endif /* COMPONENTMAIN_H_ */
