
/*
 * ComponentMain.cpp
 *
 *  Created on: Sunday, 02. February 2014 10:15AM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleMissionStatus(const config::SSM::sub::MissionStatus& msg)
{
	std::cout<< "SSM say:" << msg << std::endl;
}
	

void ComponentMain::publishStatusData(config::SSM::pub::StatusData& msg)
{
	_roscomm->publishStatusData(msg);
}
	
