
 * RosComm.h
 *
 *  Created on: Thursday, 30. January 2014 03:54PM
 *      Author: autogenerated
 */
#ifndef ROSCOMM_H_
#define ROSCOMM_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
class ComponentMain;
class RosComm {
  ComponentMain   * _comp;
  ros::NodeHandle _nh;
	ros::Subscriber _sub_TrottleEffort;
	ros::Subscriber _sub_SteeringEffort;
	ros::Subscriber _sub_JointsEffort;
	ros::Subscriber _sub_Teleoperation;
	ros::Publisher  _pub_Teleoperation;
	ros::Publisher  _pub_TrottleEffort;
	ros::Publisher  _pub_SteeringEffort;
	ros::Publisher  _pub_JointsEffort;

public:
	RosComm(ComponentMain* comp,int argc,char** argv);
	virtual ~RosComm();
	void TrottleEffortCallback(const config::LLI::sub::TrottleEffort::ConstPtr &msg);
	void SteeringEffortCallback(const config::LLI::sub::SteeringEffort::ConstPtr &msg);
	void JointsEffortCallback(const config::LLI::sub::JointsEffort::ConstPtr &msg);
	void TeleoperationCallback(const config::LLI::sub::Teleoperation::ConstPtr &msg);
	void publishTeleoperation( config::LLI::pub::Teleoperation &msg);
	void publishTrottleEffort( config::LLI::pub::TrottleEffort &msg);
	void publishSteeringEffort( config::LLI::pub::SteeringEffort &msg);
	void publishJointsEffort( config::LLI::pub::JointsEffort &msg);

};
#endif /* ROSCOMM_H_ */
