
/*
 * RosComm.h
 *
 *  Created on: Thursday, 04. June 2015 09:56AM
 *      Author: autogenerated
 */
#ifndef ROSCOMM_H_
#define ROSCOMM_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
#include <tf/tf.h>
#include <boost/thread.hpp>
class ComponentMain;
class RosComm {
  bool _inited;
  ComponentMain   * _comp;
  ros::NodeHandle _nh;
  ros::Publisher _pub_diagnostic;
  ros::Publisher _pub_connected_to_platform;
  boost::thread_group _maintains;
	ros::Subscriber _sub_EffortsTh;
	ros::Subscriber _sub_EffortsSt;
	ros::Subscriber _sub_EffortsJn;


  bool init(int argc,char** argv);
public:
	RosComm(ComponentMain* comp,int argc,char** argv);
	virtual ~RosComm();
	void EffortsThCallback(const config::LLI::sub::EffortsTh::ConstPtr &msg);
	void EffortsStCallback(const config::LLI::sub::EffortsSt::ConstPtr &msg);
	void EffortsJnCallback(const config::LLI::sub::EffortsJn::ConstPtr &msg);


	void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
	tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
	void publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report);
	void publishDiagnostic(const std_msgs::Header& header, const diagnostic_msgs::DiagnosticStatus& _report);
	void publishConnectedToPlatform(const std_msgs::Bool& msg);
	void heartbeat();
};
#endif /* ROSCOMM_H_ */
