
/*
 * ComponentMain.cpp
 *
 *  Created on: Monday, 03. February 2014 03:30PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleMap(const config::PP::sub::Map& msg)
{
	std::cout<< "PP say:" << msg << std::endl;
}
	

void ComponentMain::handleOdometry(const config::PP::sub::Odometry& msg)
{
	std::cout<< "PP say:" << msg << std::endl;
}
	

void ComponentMain::handlePPCommand(const config::PP::sub::PPCommand& msg)
{
	std::cout<< "PP say:" << msg << std::endl;
}
	

void ComponentMain::handleGlobalPath(const config::PP::sub::GlobalPath& msg)
{
	std::cout<< "PP say:" << msg << std::endl;
}
	

void ComponentMain::handleMaxSpeed(const config::PP::sub::MaxSpeed& msg)
{
	std::cout<< "PP say:" << msg << std::endl;
}
	

void ComponentMain::publishLocalPath(config::PP::pub::LocalPath& msg)
{
	_roscomm->publishLocalPath(msg);
}
	

void ComponentMain::publishPPExecutionState(config::PP::pub::PPExecutionState& msg)
{
	_roscomm->publishPPExecutionState(msg);
}
	

void ComponentMain::publishPPComponentState(config::PP::pub::PPComponentState& msg)
{
	_roscomm->publishPPComponentState(msg);
}
	
void ComponentMain::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	_roscomm->publishTransform(_tf, srcFrame, distFrame);
}
tf::StampedTransform ComponentMain::getLastTrasform(std::string srcFrame, std::string distFrame){
	return _roscomm->getLastTrasform(srcFrame, distFrame);;
}
