
/*
 * ComponentMain.cpp
 *
 *  Created on: Thursday, 27. February 2014 12:29PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
	this->receivedBladePosition = NULL;
	this->receivedWorkSeqData = NULL;
	this->receivedLocation = NULL;
	this->receivedPerVelocity = NULL;
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleWorkSeqData(const config::WSM::sub::WorkSeqData& msg)
{
	ROS_INFO("Got sequence with Task id: %s",msg.task_id.c_str());
	if(this->receivedWorkSeqData != NULL)
		delete this->receivedWorkSeqData;
	this->receivedWorkSeqData = new config::WSM::sub::WorkSeqData(msg);
	//std::cout<< "WSM say:" << msg << std::endl;
}
	

void ComponentMain::handleBladePosition(const config::WSM::sub::BladePosition& msg)
{
	if(this->receivedBladePosition != NULL)
		delete this->receivedBladePosition;
	this->receivedBladePosition = new config::WSM::sub::BladePosition(msg);
	//std::cout<< "WSM say:" << msg << std::endl;
}

void ComponentMain::handleLocation(const config::LLC::sub::Location& msg)
{

	if(this->receivedLocation != NULL)
		delete this->receivedLocation;
	this->receivedLocation = new config::LLC::sub::Location(msg);
	//std::cout<< "LLC say:" << msg.pose.pose.position.x << std::endl;
}


void ComponentMain::handlePerVelocity(const config::LLC::sub::PerVelocity& msg)
{

	if(this->receivedPerVelocity != NULL)
		delete this->receivedPerVelocity;
	this->receivedPerVelocity = new config::LLC::sub::PerVelocity(msg);

//	std::cout<< "LLC say:" << msg << std::endl;
}

void ComponentMain::publishWSMVelocity(config::WSM::pub::WSMVelocity& msg)
{
	_roscomm->publishWSMVelocity(msg);
}
	

void ComponentMain::publishBladePositionCommand(config::WSM::pub::BladePositionCommand& msg)
{
	_roscomm->publishBladePositionCommand(msg);
}


	
void ComponentMain::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	_roscomm->publishTransform(_tf, srcFrame, distFrame);
}
tf::StampedTransform ComponentMain::getLastTrasform(std::string srcFrame, std::string distFrame){
	return _roscomm->getLastTrasform(srcFrame, distFrame);
}
void ComponentMain::publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report){
	_roscomm->publishDiagnostic(_report);
}
void ComponentMain::publishDiagnostic(const std_msgs::Header& header, const diagnostic_msgs::DiagnosticStatus& _report){
	_roscomm->publishDiagnostic(header, _report);
}
