
/*
 * ComponentMain.h
 *
 *  Created on: Wednesday, 19. February 2014 04:26PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
#include <tf/tf.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleWorkSeqData(const config::WSM::sub::WorkSeqData& msg);
	void handleBladePosition(const config::WSM::sub::BladePosition& msg);
	void handlePerVelocity(const config::WSM::sub::PerVelocity& msg);
	void handleLocation(const config::WSM::sub::Location& msg);
	void publishWSMVelocity(config::WSM::pub::WSMVelocity& msg);
	void publishBladePositionCommand(config::WSM::pub::BladePositionCommand& msg);
	void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
	tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
	void publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report);
	void publishDiagnostic(const std_msgs::Header& header, const diagnostic_msgs::DiagnosticStatus& _report);
};
#endif /* COMPONENTMAIN_H_ */
