
/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 27. February 2014 12:29PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
#include <tf/tf.h>
#include <cognitao_v2/cognitao_v2.h>
#include <ros/ros.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <boost/thread.hpp>

class WsmTask;

class ComponentMain {
	bool _inited;
	ros::NodeHandle _nh;
	ros::Publisher _pub_diagnostic;
	boost::thread_group _maintains;
	ros::Subscriber _sub_WorkSeqData;
	ros::Subscriber _sub_BladePosition;
	ros::Publisher  _pub_WSMVelocity;
	ros::Publisher  _pub_BladePositionCommand;
	ros::Subscriber _sub_Location;
	ros::Subscriber _sub_PerVelocity;
	ros::Subscriber _sub_MiniMapWSM;
	ros::Publisher _plp_monitor;
	//	ros::Publisher _blade_h;
	//	ros::Publisher _Map_pub;
	bool init(int argc,char** argv);
	cognitao::bus::RosEventQueue* _events;
	boost::mutex _mt;
public:
	WsmTask* cur_mission;
	config::WSM::sub::WorkSeqData * receivedWorkSeqData;
	config::WSM::sub::BladePosition * receivedBladePosition;
	config::LLC::sub::Location * receivedLocation;
	config::LLC::sub::PerVelocity * receivedPerVelocity;
	config::WSM::sub::MiniMap *recivedMap;
	sensor_msgs::JointState *jointStates;
	double ground_heigth;
	double z_offset ;

	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleWorkSeqData(const config::WSM::sub::WorkSeqData& msg);
	void handleBladePosition(const config::WSM::sub::BladePosition& msg);
	void publishWSMVelocity(config::WSM::pub::WSMVelocity& msg);
	void publishBladePositionCommand(config::WSM::pub::BladePositionCommand& msg);
	void handleLocation(const config::LLC::sub::Location& msg);
	void handlePerVelocity(const config::LLC::sub::PerVelocity& msg);
	void handleMiniMapWSM(const config::WSM::sub::MiniMap& msg);
	void publish_monitor_time(const std_msgs::Header& msg);
//	void publish_h(const std_msgs::Float64 &msg);
//	void publish_m(const std_msgs::Float64 &msg);
	void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
	tf::StampedTransform getLastTransform(std::string srcFrame, std::string distFrame);
	void publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report);
	void publishDiagnostic(const std_msgs::Header& header, const diagnostic_msgs::DiagnosticStatus& _report);
	void heartbeat();
	void set_events(cognitao::bus::RosEventQueue* events);
	void rise_taskFinished();
	void rise_taskAborted();
	void rise_taskStarted();
	void rise_taskPaused();
	bool isClosed();
	cognitao::bus::RosEventQueue* events(){return _events;}
};

#endif /* COMPONENTMAIN_H_ */
