int8 road_blocked
int8 road_blocked_ok=0
int8 road_blocked_blocked=1

int8 no_solution
int8 no_solution_ok=0
int8 no_solution_no_solution=1

int8 static_obstacle
int8 static_obstacle_free=0
int8 static_obstacle_detected=1

int8 obstacle_avoidance
int8 obstacle_avoidance_passive=0
int8 obstacle_avoidance_started=1
int8 obstacle_avoidance_active=2
int8 obstacle_avoidance_finished=3

int8 road_shoulder
