
/*
 * RosComm.cpp
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
#include <tf/transform_broadcaster.h>
#include <tf/transform_listener.h>
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
	: _inited(init(argc, argv)), _comp(comp)
{
	_sub_Map=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"PP","Map","sub"), 10, &RosComm::MapCallback,this));
	_sub_MissionGlobalPath=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"PP","MissionGlobalPath","sub"), 10, &RosComm::MissionGlobalPathCallback,this));
	_sub_IEDPosAtt=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"PP","IEDPosAtt","sub"), 10, &RosComm::IEDPosAttCallback,this));
	_sub_PosAttVel=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"PP","PosAttVel","sub"), 10, &RosComm::PosAttVelCallback,this));
	_pub_LocalPathPlan=ros::Publisher(_nh.advertise<config::PP::pub::LocalPathPlan>(fetchParam(&_nh,"PP","LocalPathPlan","pub"),10));
}
RosComm::~RosComm()
{
}
bool RosComm::init(int argc,char** argv){
	ros::init(argc,argv,"PP_node");
	return true;
}


void RosComm::MapCallback(const config::PP::sub::Map::ConstPtr &msg)
{
	_comp->handleMap(*msg);
}
	

void RosComm::MissionGlobalPathCallback(const config::PP::sub::MissionGlobalPath::ConstPtr &msg)
{
	_comp->handleMissionGlobalPath(*msg);
}
	

void RosComm::IEDPosAttCallback(const config::PP::sub::IEDPosAtt::ConstPtr &msg)
{
	_comp->handleIEDPosAtt(*msg);
}
	

void RosComm::PosAttVelCallback(const config::PP::sub::PosAttVel::ConstPtr &msg)
{
	_comp->handlePosAttVel(*msg);
}
	

void RosComm::publishLocalPathPlan( config::PP::pub::LocalPathPlan &msg)
{
	_pub_LocalPathPlan.publish(msg);
}
	
void RosComm::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	static tf::TransformBroadcaster br;
	br.sendTransform(tf::StampedTransform(_tf, ros::Time::now(), srcFrame, distFrame));
}
tf::StampedTransform RosComm::getLastTrasform(std::string srcFrame, std::string distFrame){
	tf::StampedTransform _tf;
	static tf::TransformListener listener;
	try {
	    listener.waitForTransform(distFrame, srcFrame, ros::Time(0), ros::Duration(10.0) );
	    listener.lookupTransform(distFrame, srcFrame, ros::Time(0), _tf);
	} catch (tf::TransformException& ex) {
	    ROS_ERROR("%s",ex.what());
	}
	return _tf;
}
