
/*
 * ComponentMain.h
 *
 *  Created on: Sunday, 02. February 2014 10:01AM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleSensor_WIRE(const config::SE_R2U::sub::Sensor_WIRE& msg);
	void handleSensor_INS(const config::SE_R2U::sub::Sensor_INS& msg);
	void handleSensor_GPS(const config::SE_R2U::sub::Sensor_GPS& msg);

};
#endif /* COMPONENTMAIN_H_ */
