
/*
 * ComponentMain.cpp
 *
 *  Created on: Thursday, 30. January 2014 04:16PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleSensor_WIRE(const config::SE_R2U::sub::Sensor_WIRE& msg)
{
	std::cout<< "SE_R2U say:" << msg.data << std::endl;
}
	

void ComponentMain::handleSensor_INSGPS(const config::SE_R2U::sub::Sensor_INSGPS& msg)
{
	std::cout<< "SE_R2U say:" << msg.data << std::endl;
}
	

