
/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 30. January 2014 04:16PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleSensor_WIRE(const config::SE_R2U::sub::Sensor_WIRE& msg);
	void handleSensor_INSGPS(const config::SE_R2U::sub::Sensor_INSGPS& msg);

};
#endif /* COMPONENTMAIN_H_ */
