
/*
 * RosComm.h
 *
 *  Created on: Thursday, 30. January 2014 04:16PM
 *      Author: autogenerated
 */
#ifndef ROSCOMM_H_
#define ROSCOMM_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
class ComponentMain;
class RosComm {
  ComponentMain   * _comp;
  ros::NodeHandle _nh;
	ros::Subscriber _sub_LocalPathPlan;
	ros::Subscriber _sub_MiniMap;
	ros::Subscriber _sub_PosAttVel;
	ros::Publisher  _pub_RPPPath;

public:
	RosComm(ComponentMain* comp,int argc,char** argv);
	virtual ~RosComm();
	void LocalPathPlanCallback(const config::RPP::sub::LocalPathPlan::ConstPtr &msg);
	void MiniMapCallback(const config::RPP::sub::MiniMap::ConstPtr &msg);
	void PosAttVelCallback(const config::RPP::sub::PosAttVel::ConstPtr &msg);
	void publishRPPPath( config::RPP::pub::RPPPath &msg);

};
#endif /* ROSCOMM_H_ */
