
/*
 * RosComm.cpp
 *
 *  Created on: Thursday, 30. January 2014 03:54PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
{
  ros::init(argc,argv,"PP_node");
  _comp=comp;
	_sub_Map=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"RPP","LocalPathPlan","sub"), 10, &RosComm::LocalPathPlanCallback,this));
	_sub_Map=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"RPP","MiniMap","sub"), 10, &RosComm::MiniMapCallback,this));
	_sub_Map=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"RPP","PosAttVel","sub"), 10, &RosComm::PosAttVelCallback,this));
	_pub_RPPPath=ros::Publisher(_nh.advertise<config::RPP::pub::RPPPath>(fetchParam(&_nh,"RPP","RPPPath","pub"),10));
}
RosComm::~RosComm()
{
}

void RosComm::LocalPathPlanCallback(const config::RPP::sub::LocalPathPlan::ConstPtr &msg)
{
	_comp->handleLocalPathPlan(*msg);
}
	

void RosComm::MiniMapCallback(const config::RPP::sub::MiniMap::ConstPtr &msg)
{
	_comp->handleMiniMap(*msg);
}
	

void RosComm::PosAttVelCallback(const config::RPP::sub::PosAttVel::ConstPtr &msg)
{
	_comp->handlePosAttVel(*msg);
}
	

void RosComm::publishRPPPath( config::RPP::pub::RPPPath &msg)
{
	_pub_RPPPath.publish(msg);
}
	
