
/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 30. January 2014 03:54PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleLocalPathPlan(const config::RPP::sub::LocalPathPlan& msg);
	void handleMiniMap(const config::RPP::sub::MiniMap& msg);
	void handlePosAttVel(const config::RPP::sub::PosAttVel& msg);
	void publishRPPPath(config::RPP::pub::RPPPath& msg);
};
#endif /* COMPONENTMAIN_H_ */
