
/*
 * ComponentMain.cpp
 *
 *  Created on: Thursday, 30. January 2014 03:54PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleLocalPathPlan(config::RPP::sub::LocalPathPlan& msg)
{
	std::cout<< "RPP say:" << msg.data << std::endl;
}
	

void ComponentMain::handleMiniMap(config::RPP::sub::MiniMap& msg)
{
	std::cout<< "RPP say:" << msg.data << std::endl;
}
	

void ComponentMain::handlePosAttVel(config::RPP::sub::PosAttVel& msg)
{
	std::cout<< "RPP say:" << msg.data << std::endl;
}
	

void ComponentMain::publishRPPPath(config::RPP::pub::RPPPath& msg)
{
	_roscomm->publishRPPPath(msg);
}
	
