
/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 30. January 2014 04:16PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleBladePosition(const config::MAP::sub::BladePosition& msg);
	void handlePosAttVel(const config::MAP::sub::PosAttVel& msg);
	void handleLaser(const config::MAP::sub::Laser& msg);
	void handleCamera(const config::MAP::sub::Camera& msg);
	void publishMap(config::MAP::pub::Map& msg);
	void publishMiniMap(config::MAP::pub::MiniMap& msg);
};
#endif /* COMPONENTMAIN_H_ */
