
/*
 * ComponentMain.h
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
#include <tf/tf.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleBladePosition(const config::MAP::sub::BladePosition& msg);
	void handlePosAttVel(const config::MAP::sub::PosAttVel& msg);
	void handleLaser(const config::MAP::sub::Laser& msg);
	void handleCamera(const config::MAP::sub::Camera& msg);
	void publishMap(config::MAP::pub::Map& msg);
	void publishMiniMap(config::MAP::pub::MiniMap& msg);
  void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
  tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
};
#endif /* COMPONENTMAIN_H_ */
