
/*
 * RosComm.h
 *
 *  Created on: Thursday, 06. February 2014 04:09PM
 *      Author: autogenerated
 */
#ifndef ROSCOMM_H_
#define ROSCOMM_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
#include <tf/tf.h>
class ComponentMain;
class RosComm {
  bool _inited;
  ComponentMain   * _comp;
  ros::NodeHandle _nh;
	ros::Subscriber _sub_WSMSpeed;
	ros::Subscriber _sub_BladePositionCommand;
	ros::Subscriber _sub_WPDSpeed;
	ros::Subscriber _sub_Odometry;
	ros::Subscriber _sub_LLCCommand;
	ros::Subscriber _sub_TeleoperationThrottle;
	ros::Subscriber _sub_TeleoperationSteering;
	ros::Subscriber _sub_TeleoperationJoints;
	ros::Publisher  _pub_TrottleEffort;
	ros::Publisher  _pub_SteeringEffort;
	ros::Publisher  _pub_JointsEffort;
	ros::Publisher  _pub_LLCPlatformState;
	ros::Publisher  _pub_LLCComponentState;

  bool init(int argc,char** argv);
public:
	RosComm(ComponentMain* comp,int argc,char** argv);
	virtual ~RosComm();
	void WSMSpeedCallback(const config::LLC::sub::WSMSpeed::ConstPtr &msg);
	void BladePositionCommandCallback(const config::LLC::sub::BladePositionCommand::ConstPtr &msg);
	void WPDSpeedCallback(const config::LLC::sub::WPDSpeed::ConstPtr &msg);
	void OdometryCallback(const config::LLC::sub::Odometry::ConstPtr &msg);
	void LLCCommandCallback(const config::LLC::sub::LLCCommand::ConstPtr &msg);
	void TeleoperationThrottleCallback(const config::LLC::sub::TeleoperationThrottle::ConstPtr &msg);
	void TeleoperationSteeringCallback(const config::LLC::sub::TeleoperationSteering::ConstPtr &msg);
	void TeleoperationJointsCallback(const config::LLC::sub::TeleoperationJoints::ConstPtr &msg);
	void publishTrottleEffort( config::LLC::pub::TrottleEffort &msg);
	void publishSteeringEffort( config::LLC::pub::SteeringEffort &msg);
	void publishJointsEffort( config::LLC::pub::JointsEffort &msg);
	void publishLLCPlatformState( config::LLC::pub::LLCPlatformState &msg);
	void publishLLCComponentState( config::LLC::pub::LLCComponentState &msg);

  void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
  tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
};
#endif /* ROSCOMM_H_ */
