
/*
 * RosComm.cpp
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
#include <tf/transform_broadcaster.h>
#include <tf/transform_listener.h>
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
	: _inited(init(argc, argv)), _comp(comp)
{
	_sub_Speed=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"LLC","Speed","sub"), 10, &RosComm::SpeedCallback,this));
	_sub_TrottleEffort=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"LLC","TrottleEffort","sub"), 10, &RosComm::TrottleEffortCallback,this));
	_sub_SteeringEffort=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"LLC","SteeringEffort","sub"), 10, &RosComm::SteeringEffortCallback,this));
	_sub_JointsEffort=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"LLC","JointsEffort","sub"), 10, &RosComm::JointsEffortCallback,this));
	_sub_Teleoperation=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"LLC","Teleoperation","sub"), 10, &RosComm::TeleoperationCallback,this));
	_pub_TrottleEffort=ros::Publisher(_nh.advertise<config::LLC::pub::TrottleEffort>(fetchParam(&_nh,"LLC","TrottleEffort","pub"),10));
	_pub_SteeringEffort=ros::Publisher(_nh.advertise<config::LLC::pub::SteeringEffort>(fetchParam(&_nh,"LLC","SteeringEffort","pub"),10));
	_pub_JointsEffort=ros::Publisher(_nh.advertise<config::LLC::pub::JointsEffort>(fetchParam(&_nh,"LLC","JointsEffort","pub"),10));
}
RosComm::~RosComm()
{
}
bool RosComm::init(int argc,char** argv){
	ros::init(argc,argv,"LLC_node");
	return true;
}


void RosComm::SpeedCallback(const config::LLC::sub::Speed::ConstPtr &msg)
{
	_comp->handleSpeed(*msg);
}
	

void RosComm::TrottleEffortCallback(const config::LLC::sub::TrottleEffort::ConstPtr &msg)
{
	_comp->handleTrottleEffort(*msg);
}
	

void RosComm::SteeringEffortCallback(const config::LLC::sub::SteeringEffort::ConstPtr &msg)
{
	_comp->handleSteeringEffort(*msg);
}
	

void RosComm::JointsEffortCallback(const config::LLC::sub::JointsEffort::ConstPtr &msg)
{
	_comp->handleJointsEffort(*msg);
}
	

void RosComm::TeleoperationCallback(const config::LLC::sub::Teleoperation::ConstPtr &msg)
{
	_comp->handleTeleoperation(*msg);
}
	

void RosComm::publishTrottleEffort( config::LLC::pub::TrottleEffort &msg)
{
	_pub_TrottleEffort.publish(msg);
}
	

void RosComm::publishSteeringEffort( config::LLC::pub::SteeringEffort &msg)
{
	_pub_SteeringEffort.publish(msg);
}
	

void RosComm::publishJointsEffort( config::LLC::pub::JointsEffort &msg)
{
	_pub_JointsEffort.publish(msg);
}
	
void RosComm::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	static tf::TransformBroadcaster br;
	br.sendTransform(tf::StampedTransform(_tf, ros::Time::now(), srcFrame, distFrame));
}
tf::StampedTransform RosComm::getLastTrasform(std::string srcFrame, std::string distFrame){
	tf::StampedTransform _tf;
	static tf::TransformListener listener;
	try {
	    listener.waitForTransform(distFrame, srcFrame, ros::Time(0), ros::Duration(10.0) );
	    listener.lookupTransform(distFrame, srcFrame, ros::Time(0), _tf);
	} catch (tf::TransformException& ex) {
	    ROS_ERROR("%s",ex.what());
	}
	return _tf;
}
