/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 27. February 2014 12:29PM
 *      Author: autogenerated
 */
#ifndef DISPLAY_IMAGE_H
#define DISPLAY_IMAGE_H

#include <opencv2/opencv.hpp>
#include <iostream>
#include <stdio.h>
#include <cmath>
#include <vector>

using namespace std;
using namespace cv;

/** *********************
	printEntropy
 ** *********************/
void printEntropy();

/** *********************
	calcEntropy
 ** *********************/
void calcEntropy(Mat w, int l, int k, int cut_percents, int down_percents);

/** ****************************
	createEntropyImage
 ** ****************************/
Mat createEntropyImage();

/** *********************
	Erode
 ** *********************/
Mat Erosion(Mat src, double factor);


/** *********************
	Dilate
 ** *********************/
Mat Dilation(Mat src, double factor);

/** ********************************
 *  find lines :
 ** ********************************/
void findLines(Mat m, vector<Point> contour, Vec4i hierarchy, Scalar color);


/** *******************************
 *  detectRoad:
 ** *******************************/
vector<double> detectRoad(Mat read_image, int cut_p, int down_p, int toDebug);


#endif 
