
/*
 * ComponentMain.cpp
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleCamera(const config::VO::sub::Camera& msg)
{
	std::cout<< "VO say:" << msg << std::endl;
}
	

void ComponentMain::handleINS(const config::VO::sub::INS& msg)
{
	std::cout<< "VO say:" << msg << std::endl;
}
	

void ComponentMain::handleTF(const config::VO::sub::TF& msg)
{
	std::cout<< "VO say:" << msg << std::endl;
}
	

void ComponentMain::publishPosAttVel(config::VO::pub::PosAttVel& msg)
{
	_roscomm->publishPosAttVel(msg);
}
	
void ComponentMain::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	_roscomm->publishTransform(_tf, srcFrame, distFrame);
}
tf::StampedTransform ComponentMain::getLastTrasform(std::string srcFrame, std::string distFrame){
	return _roscomm->getLastTrasform(srcFrame, distFrame);;
}
