
/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 30. January 2014 06:41PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleCamera(const config::VO::sub::Camera& msg);
	void handleINS(const config::VO::sub::INS& msg);
	void handleTF(const config::VO::sub::TF& msg);
	void publishPosAttVel(config::VO::pub::PosAttVel& msg);
};
#endif /* COMPONENTMAIN_H_ */
