
/*
 * RosComm.cpp
 *
 *  Created on: Monday, 03. February 2014 03:30PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
#include <tf/transform_broadcaster.h>
#include <tf/transform_listener.h>
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
	: _inited(init(argc, argv)), _comp(comp)
{
	_sub_Odometry=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"IEDSIM","Odometry","sub"), 10, &RosComm::OdometryCallback,this));
	_sub_IEDDetectionEvent=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"IEDSIM","IEDDetectionEvent","sub"), 10, &RosComm::IEDDetectionEventCallback,this));
	_sub_IEDLocation=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"IEDSIM","IEDLocation","sub"), 10, &RosComm::IEDLocationCallback,this));
	_sub_IEDSIMCommand=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"IEDSIM","IEDSIMCommand","sub"), 10, &RosComm::IEDSIMCommandCallback,this));
	_pub_IEDDetectionEvent=ros::Publisher(_nh.advertise<config::IEDSIM::pub::IEDDetectionEvent>(fetchParam(&_nh,"IEDSIM","IEDDetectionEvent","pub"),10));
	_pub_IEDLocation=ros::Publisher(_nh.advertise<config::IEDSIM::pub::IEDLocation>(fetchParam(&_nh,"IEDSIM","IEDLocation","pub"),10));
}
RosComm::~RosComm()
{
}
bool RosComm::init(int argc,char** argv){
	ros::init(argc,argv,"IEDSIM_node");
	return true;
}


void RosComm::OdometryCallback(const config::IEDSIM::sub::Odometry::ConstPtr &msg)
{
	_comp->handleOdometry(*msg);
}
	

void RosComm::IEDDetectionEventCallback(const config::IEDSIM::sub::IEDDetectionEvent::ConstPtr &msg)
{
	_comp->handleIEDDetectionEvent(*msg);
}
	

void RosComm::IEDLocationCallback(const config::IEDSIM::sub::IEDLocation::ConstPtr &msg)
{
	_comp->handleIEDLocation(*msg);
}
	

void RosComm::IEDSIMCommandCallback(const config::IEDSIM::sub::IEDSIMCommand::ConstPtr &msg)
{
	_comp->handleIEDSIMCommand(*msg);
}
	

void RosComm::publishIEDDetectionEvent( config::IEDSIM::pub::IEDDetectionEvent &msg)
{
	_pub_IEDDetectionEvent.publish(msg);
}
	

void RosComm::publishIEDLocation( config::IEDSIM::pub::IEDLocation &msg)
{
	_pub_IEDLocation.publish(msg);
}
	
void RosComm::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	static tf::TransformBroadcaster br;
	br.sendTransform(tf::StampedTransform(_tf, ros::Time::now(), srcFrame, distFrame));
}
tf::StampedTransform RosComm::getLastTrasform(std::string srcFrame, std::string distFrame){
	tf::StampedTransform _tf;
	static tf::TransformListener listener;
	try {
	    listener.waitForTransform(distFrame, srcFrame, ros::Time(0), ros::Duration(10.0) );
	    listener.lookupTransform(distFrame, srcFrame, ros::Time(0), _tf);
	} catch (tf::TransformException& ex) {
	    ROS_ERROR("%s",ex.what());
	}
	return _tf;
}
