
/*
 * RosComm.h
 *
 *  Created on: Thursday, 06. February 2014 04:09PM
 *      Author: autogenerated
 */
#ifndef ROSCOMM_H_
#define ROSCOMM_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
#include <tf/tf.h>
class ComponentMain;
class RosComm {
  bool _inited;
  ComponentMain   * _comp;
  ros::NodeHandle _nh;
	ros::Subscriber _sub_Odometry;
	ros::Subscriber _sub_IEDLocation;
	ros::Subscriber _sub_IEDSIMCommand;
	ros::Publisher  _pub_IEDLocation;
	ros::Publisher  _pub_IEDSIMComponentState;

  bool init(int argc,char** argv);
public:
	RosComm(ComponentMain* comp,int argc,char** argv);
	virtual ~RosComm();
	void OdometryCallback(const config::IEDSIM::sub::Odometry::ConstPtr &msg);
	void IEDLocationCallback(const config::IEDSIM::sub::IEDLocation::ConstPtr &msg);
	void IEDSIMCommandCallback(const config::IEDSIM::sub::IEDSIMCommand::ConstPtr &msg);
	void publishIEDLocation( config::IEDSIM::pub::IEDLocation &msg);
	void publishIEDSIMComponentState( config::IEDSIM::pub::IEDSIMComponentState &msg);

  void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
  tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
};
#endif /* ROSCOMM_H_ */
