
/*
 * RosComm.cpp
 *
 *  Created on: Thursday, 30. January 2014 06:41PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
{
  ros::init(argc,argv,"PP_node");
  _comp=comp;
	_sub_IEDDetectionEvent=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"IEDSIM","IEDDetectionEvent","sub"), 10, &RosComm::IEDDetectionEventCallback,this));
	_sub_IEDLocation=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"IEDSIM","IEDLocation","sub"), 10, &RosComm::IEDLocationCallback,this));
	_pub_IEDDetectionEvent=ros::Publisher(_nh.advertise<config::IEDSIM::pub::IEDDetectionEvent>(fetchParam(&_nh,"IEDSIM","IEDDetectionEvent","pub"),10));
	_pub_IEDLocation=ros::Publisher(_nh.advertise<config::IEDSIM::pub::IEDLocation>(fetchParam(&_nh,"IEDSIM","IEDLocation","pub"),10));
}
RosComm::~RosComm()
{
}

void RosComm::IEDDetectionEventCallback(const config::IEDSIM::sub::IEDDetectionEvent::ConstPtr &msg)
{
	_comp->handleIEDDetectionEvent(*msg);
}
	

void RosComm::IEDLocationCallback(const config::IEDSIM::sub::IEDLocation::ConstPtr &msg)
{
	_comp->handleIEDLocation(*msg);
}
	

void RosComm::publishIEDDetectionEvent( config::IEDSIM::pub::IEDDetectionEvent &msg)
{
	_pub_IEDDetectionEvent.publish(msg);
}
	

void RosComm::publishIEDLocation( config::IEDSIM::pub::IEDLocation &msg)
{
	_pub_IEDLocation.publish(msg);
}
	
