
/*
 * RosComm.cpp
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
#include <tf/transform_broadcaster.h>
#include <tf/transform_listener.h>
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
	: _inited(init(argc, argv)), _comp(comp)
{
	_sub_Sensor_SICK=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2RS","Sensor_SICK","sub"), 10, &RosComm::Sensor_SICKCallback,this));
	_sub_Sensor_IBEO=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2RS","Sensor_IBEO","sub"), 10, &RosComm::Sensor_IBEOCallback,this));
	_sub_Sensor_CAM_R=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2RS","Sensor_CAM_R","sub"), 10, &RosComm::Sensor_CAM_RCallback,this));
	_sub_Sensor_CAM_L=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2RS","Sensor_CAM_L","sub"), 10, &RosComm::Sensor_CAM_LCallback,this));

}
RosComm::~RosComm()
{
}
bool RosComm::init(int argc,char** argv){
	ros::init(argc,argv,"SE_R2RS_node");
	return true;
}


void RosComm::Sensor_SICKCallback(const config::SE_R2RS::sub::Sensor_SICK::ConstPtr &msg)
{
	_comp->handleSensor_SICK(*msg);
}
	

void RosComm::Sensor_IBEOCallback(const config::SE_R2RS::sub::Sensor_IBEO::ConstPtr &msg)
{
	_comp->handleSensor_IBEO(*msg);
}
	

void RosComm::Sensor_CAM_RCallback(const config::SE_R2RS::sub::Sensor_CAM_R::ConstPtr &msg)
{
	_comp->handleSensor_CAM_R(*msg);
}
	

void RosComm::Sensor_CAM_LCallback(const config::SE_R2RS::sub::Sensor_CAM_L::ConstPtr &msg)
{
	_comp->handleSensor_CAM_L(*msg);
}
	

void RosComm::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	static tf::TransformBroadcaster br;
	br.sendTransform(tf::StampedTransform(_tf, ros::Time::now(), srcFrame, distFrame));
}
tf::StampedTransform RosComm::getLastTrasform(std::string srcFrame, std::string distFrame){
	tf::StampedTransform _tf;
	static tf::TransformListener listener;
	try {
	    listener.waitForTransform(distFrame, srcFrame, ros::Time(0), ros::Duration(10.0) );
	    listener.lookupTransform(distFrame, srcFrame, ros::Time(0), _tf);
	} catch (tf::TransformException& ex) {
	    ROS_ERROR("%s",ex.what());
	}
	return _tf;
}
