
/*
 * RosComm.cpp
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
#include <tf/transform_broadcaster.h>
#include <tf/transform_listener.h>
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
	: _inited(init(argc, argv)), _comp(comp)
{
	_sub_Sensor_WIRE=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2U","Sensor_WIRE","sub"), 10, &RosComm::Sensor_WIRECallback,this));
	_sub_Sensor_INS=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2U","Sensor_INS","sub"), 10, &RosComm::Sensor_INSCallback,this));
	_sub_Sensor_GPS=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2U","Sensor_GPS","sub"), 10, &RosComm::Sensor_GPSCallback,this));

}
RosComm::~RosComm()
{
}
bool RosComm::init(int argc,char** argv){
	ros::init(argc,argv,"SE_R2U_node");
	return true;
}


void RosComm::Sensor_WIRECallback(const config::SE_R2U::sub::Sensor_WIRE::ConstPtr &msg)
{
	_comp->handleSensor_WIRE(*msg);
}
	

void RosComm::Sensor_INSCallback(const config::SE_R2U::sub::Sensor_INS::ConstPtr &msg)
{
	_comp->handleSensor_INS(*msg);
}
	

void RosComm::Sensor_GPSCallback(const config::SE_R2U::sub::Sensor_GPS::ConstPtr &msg)
{
	_comp->handleSensor_GPS(*msg);
}
	

void RosComm::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	static tf::TransformBroadcaster br;
	br.sendTransform(tf::StampedTransform(_tf, ros::Time::now(), srcFrame, distFrame));
}
tf::StampedTransform RosComm::getLastTrasform(std::string srcFrame, std::string distFrame){
	tf::StampedTransform _tf;
	static tf::TransformListener listener;
	try {
	    listener.waitForTransform(distFrame, srcFrame, ros::Time(0), ros::Duration(10.0) );
	    listener.lookupTransform(distFrame, srcFrame, ros::Time(0), _tf);
	} catch (tf::TransformException& ex) {
	    ROS_ERROR("%s",ex.what());
	}
	return _tf;
}
