
/*
 * RosComm.cpp
 *
 *  Created on: Thursday, 30. January 2014 06:41PM
 *      Author: autogenerated
 */
#include <ros/ros.h>
#include <std_msgs/String.h>
#include "RosComm.h"
#include "../component/ComponentMain.h"
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include "ParameterHandler.h"
RosComm::RosComm(ComponentMain* comp,int argc,char** argv)
{
  ros::init(argc,argv,"PP_node");
  _comp=comp;
	_sub_Sensor_WIRE=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2U","Sensor_WIRE","sub"), 10, &RosComm::Sensor_WIRECallback,this));
	_sub_Sensor_INS=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2U","Sensor_INS","sub"), 10, &RosComm::Sensor_INSCallback,this));
	_sub_Sensor_GPS=ros::Subscriber(_nh.subscribe(fetchParam(&_nh,"SE_R2U","Sensor_GPS","sub"), 10, &RosComm::Sensor_GPSCallback,this));

}
RosComm::~RosComm()
{
}

void RosComm::Sensor_WIRECallback(const config::SE_R2U::sub::Sensor_WIRE::ConstPtr &msg)
{
	_comp->handleSensor_WIRE(*msg);
}
	

void RosComm::Sensor_INSCallback(const config::SE_R2U::sub::Sensor_INS::ConstPtr &msg)
{
	_comp->handleSensor_INS(*msg);
}
	

void RosComm::Sensor_GPSCallback(const config::SE_R2U::sub::Sensor_GPS::ConstPtr &msg)
{
	_comp->handleSensor_GPS(*msg);
}
	

