
 * RosComm.h
 *
 *  Created on: Thursday, 30. January 2014 03:54PM
 *      Author: autogenerated
 */
#ifndef ROSCOMM_H_
#define ROSCOMM_H_
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <string>       // std::string
#include <iostream>     // std::cout
#include <sstream>
#include <ParameterTypes.h>
class ComponentMain;
class RosComm {
  ComponentMain   * _comp;
  ros::NodeHandle _nh;
	ros::Subscriber _sub_Sensor_WIRE;
	ros::Subscriber _sub_Sensor_INSGPS;


public:
	RosComm(ComponentMain* comp,int argc,char** argv);
	virtual ~RosComm();
	void Sensor_WIRECallback(const config::SE_R2U::sub::Sensor_WIRE::ConstPtr &msg);
	void Sensor_INSGPSCallback(const config::SE_R2U::sub::Sensor_INSGPS::ConstPtr &msg);


};
#endif /* ROSCOMM_H_ */
