
/*
 * ComponentMain.h
 *
 *  Created on: Sunday, 02. February 2014 03:25PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
#include <tf/tf.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handleSensor_SICK(const config::SE_R2RS::sub::Sensor_SICK& msg);
	void handleSensor_IBEO(const config::SE_R2RS::sub::Sensor_IBEO& msg);
	void handleSensor_CAM_R(const config::SE_R2RS::sub::Sensor_CAM_R& msg);
	void handleSensor_CAM_L(const config::SE_R2RS::sub::Sensor_CAM_L& msg);

  void publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame);
  tf::StampedTransform getLastTrasform(std::string srcFrame, std::string distFrame);
};
#endif /* COMPONENTMAIN_H_ */
