
/*
 * ComponentMain.cpp
 *
 *  Created on: Thursday, 30. January 2014 03:54PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleSensor_SICK(config::SE_R2RS::sub::Sensor_SICK& msg)
{
	std::cout<< "SE_R2RS say:" << msg.data << std::endl;
}
	

void ComponentMain::handleSensor_IBEO(config::SE_R2RS::sub::Sensor_IBEO& msg)
{
	std::cout<< "SE_R2RS say:" << msg.data << std::endl;
}
	

void ComponentMain::handleSensor_CAM_R(config::SE_R2RS::sub::Sensor_CAM_R& msg)
{
	std::cout<< "SE_R2RS say:" << msg.data << std::endl;
}
	

void ComponentMain::handleSensor_CAM_L(config::SE_R2RS::sub::Sensor_CAM_L& msg)
{
	std::cout<< "SE_R2RS say:" << msg.data << std::endl;
}
	

