
/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 30. January 2014 04:16PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
public:
	ComponentMain(int argc,char** argv);
	virtual ~ComponentMain();
	void handlePosAttVel(const config::LOC::sub::PosAttVel& msg);
	void handlePositionUpdate(const config::LOC::sub::PositionUpdate& msg);
	void publishPosAttVel(config::LOC::pub::PosAttVel& msg);
};
#endif /* COMPONENTMAIN_H_ */
