
/*
 * ComponentMain.cpp
 *
 *  Created on: Monday, 03. February 2014 03:30PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleVOOdometry(const config::LOC::sub::VOOdometry& msg)
{
	std::cout<< "LOC say:" << msg << std::endl;
}
	

void ComponentMain::handleGPS(const config::LOC::sub::GPS& msg)
{
	std::cout<< "LOC say:" << msg << std::endl;
}
	

void ComponentMain::handleINS(const config::LOC::sub::INS& msg)
{
	std::cout<< "LOC say:" << msg << std::endl;
}
	

void ComponentMain::handlePositionUpdate(const config::LOC::sub::PositionUpdate& msg)
{
	std::cout<< "LOC say:" << msg << std::endl;
}
	

void ComponentMain::handleLOCCommand(const config::LOC::sub::LOCCommand& msg)
{
	std::cout<< "LOC say:" << msg << std::endl;
}
	

void ComponentMain::publishOdometry(config::LOC::pub::Odometry& msg)
{
	_roscomm->publishOdometry(msg);
}
	

void ComponentMain::publishLOCState(config::LOC::pub::LOCState& msg)
{
	_roscomm->publishLOCState(msg);
}
	

void ComponentMain::publishLOCComponentState(config::LOC::pub::LOCComponentState& msg)
{
	_roscomm->publishLOCComponentState(msg);
}
	
void ComponentMain::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	_roscomm->publishTransform(_tf, srcFrame, distFrame);
}
tf::StampedTransform ComponentMain::getLastTrasform(std::string srcFrame, std::string distFrame){
	return _roscomm->getLastTrasform(srcFrame, distFrame);;
}
