
/*
 * ComponentMain.cpp
 *
 *  Created on: Sunday, 02. February 2014 10:15AM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handlePosAttVel(const config::LOC::sub::PosAttVel& msg)
{
	std::cout<< "LOC say:" << msg << std::endl;
}
	

void ComponentMain::handlePositionUpdate(const config::LOC::sub::PositionUpdate& msg)
{
	std::cout<< "LOC say:" << msg << std::endl;
}
	

void ComponentMain::publishPosAttVel(config::LOC::pub::PosAttVel& msg)
{
	_roscomm->publishPosAttVel(msg);
}
	
