
/*
 * ComponentMain.cpp
 *
 *  Created on: Thursday, 27. February 2014 12:29PM
 *      Author: autogenerated
 */
#include "ComponentMain.h"
#include "../roscomm/RosComm.h"
ComponentMain::ComponentMain(int argc,char** argv)
{
	_roscomm = new RosComm(this,argc, argv);
	_events = 0;
}
ComponentMain::~ComponentMain() {
	if(_roscomm) delete _roscomm; _roscomm=0;
}

void ComponentMain::handleIEDLocation(const config::OCU::sub::IEDLocation& msg)
{
//	std::cout<< "OCU say:" << msg << std::endl;
}
	

void ComponentMain::handleMissionAcceptance(const config::OCU::sub::MissionAcceptance& msg)
{
//	std::cout<< "OCU say:" << msg << std::endl;
}
	

void ComponentMain::handleLocalPath(const config::OCU::sub::LocalPath& msg)
{
//	std::cout<< "OCU say:" << msg << std::endl;
}
	

void ComponentMain::handleBladePosition(const config::OCU::sub::BladePosition& msg)
{
//	std::cout<< "OCU say:" << msg << std::endl;
}
	

void ComponentMain::handleMap(const config::OCU::sub::Map& msg)
{
//	std::cout<< "OCU say:" << msg << std::endl;
}
	

void ComponentMain::handleLocation(const config::OCU::sub::Location& msg)
{
//	std::cout<< "OCU say:" << msg << std::endl;
}
	

void ComponentMain::handlePerVelocity(const config::OCU::sub::PerVelocity& msg)
{
//	std::cout<< "OCU say:" << msg << std::endl;
}
	

void ComponentMain::publishCustomIED(config::OCU::pub::CustomIED& msg)
{
	_roscomm->publishCustomIED(msg);
}
	

void ComponentMain::publishPositionUpdate(config::OCU::pub::PositionUpdate& msg)
{
	_roscomm->publishPositionUpdate(msg);
}
	

void ComponentMain::publishAssignNavTask(config::OCU::pub::AssignNavTask& msg)
{
	_roscomm->publishAssignNavTask(msg);
}
	

void ComponentMain::publishAssignManTask(config::OCU::pub::AssignManTask& msg)
{
	_roscomm->publishAssignManTask(msg);
}
	

void ComponentMain::publishAssignMission(config::OCU::pub::AssignMission& msg)
{
	_roscomm->publishAssignMission(msg);
}
	
void ComponentMain::publishTransform(const tf::Transform& _tf, std::string srcFrame, std::string distFrame){
	_roscomm->publishTransform(_tf, srcFrame, distFrame);
}
tf::StampedTransform ComponentMain::getLastTrasform(std::string srcFrame, std::string distFrame){
	return _roscomm->getLastTrasform(srcFrame, distFrame);
}
void ComponentMain::publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report){
	_roscomm->publishDiagnostic(_report);
}
void ComponentMain::publishDiagnostic(const std_msgs::Header& header, const diagnostic_msgs::DiagnosticStatus& _report){
	_roscomm->publishDiagnostic(header, _report);
}

void ComponentMain::set_events(cognitao::bus::RosEventQueue* events){
	boost::mutex::scoped_lock l(_mt);
	_events = events;
}
void ComponentMain::rise_taskFinished(){
	boost::mutex::scoped_lock l(_mt);
	if(not _events) return;
	_events->rise(cognitao::bus::Event("/CompleteTask"));
}
void ComponentMain::rise_taskAborted(){
	boost::mutex::scoped_lock l(_mt);
	if(not _events) return;
	_events->rise(cognitao::bus::Event("/AbortTask"));
}
void ComponentMain::rise_taskStarted(){
	boost::mutex::scoped_lock l(_mt);
	if(not _events) return;
	_events->rise(cognitao::bus::Event("/TaskIsStarted"));
}
void ComponentMain::rise_taskPaused(){
	boost::mutex::scoped_lock l(_mt);
	if(not _events) return;
	_events->rise(cognitao::bus::Event("/TaskIsAborted"));
}
bool ComponentMain::isClosed() {
	return _events->is_closed();
}
