/*
 * ComponentMain.h
 *
 *  Created on: Thursday, 27. February 2014 12:29PM
 *      Author: autogenerated
 */
#ifndef COMPONENTMAIN_H_
#define COMPONENTMAIN_H_
#include <std_msgs/String.h>
#include <ParameterTypes.h>
#include <tf/tf.h>
#include <cognitao_v2/cognitao_v2.h>
class RosComm;
class ComponentMain {
	RosComm* _roscomm;
	cognitao::bus::RosEventQueue* _events;
	boost::mutex _mt;
public:
	//config::LLC::sub::PerVelocity Per_measured_speed ;	/* real measured speed */
	geometry_msgs::Twist Per_measured_speed;
	config::LLC::sub::WSMVelocity WSM_desired_speed; /* WSM desired vel. - on work sequence mode */
	config::LLC::sub::WPDVelocity WPD_desired_speed; /* WPD desired vel. - on driving mode */
	config::LLC::sub::BladePositionCommand Blade_angle; /* WSM desired supporter positon */
	config::LLC::sub::Location Per_pose; /* Per location */
	int t_flag;

	ComponentMain(int argc, char** argv);
	virtual ~ComponentMain();
	void handleWPDVelocity(const config::LLC::sub::WPDVelocity& msg);
	void handleWSMVelocity(const config::LLC::sub::WSMVelocity& msg);
	void handleBladePositionCommand(
			const config::LLC::sub::BladePositionCommand& msg);
	void handleLocation(const config::LLC::sub::Location& msg);
	void handlePerVelocity(const config::LLC::sub::PerVelocity& msg);
	void publishEffortsTh(config::LLC::pub::EffortsTh& msg);
	void publishEffortsSt(config::LLC::pub::EffortsSt& msg);
	void publishEffortsJn(sensor_msgs::JointState& msg);
	void publishTransform(const tf::Transform& _tf, std::string srcFrame,
			std::string distFrame);
	tf::StampedTransform getLastTrasform(std::string srcFrame,
			std::string distFrame);
	void publishDiagnostic(const diagnostic_msgs::DiagnosticStatus& _report);
	void publishDiagnostic(const std_msgs::Header& header,
			const diagnostic_msgs::DiagnosticStatus& _report);
	void set_events(cognitao::bus::RosEventQueue* events);
	void rise_taskFinished();
	void rise_taskAborted();
	void rise_taskStarted();
	void rise_taskPaused();
	bool isClosed();
};
#endif /* COMPONENTMAIN_H_ */

